[package]
cairo-version = "2.2.0"
name = "zdefender"
version = "0.0.0"

[cairo]
sierra-replace-ids = true

[dependencies]
starknet = ">=2.2.0"
alexandria_data_structures = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "46c8d8ab9e3bfb68b70a29b3246f809cd8bf70e4" }
dojo = { git = "https://github.com/dojoengine/dojo.git", tag = "v0.3.1" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "http://localhost:5050/"
account_address = "0x517ececd29116499f4a1b64b094da79ba08dfd54a3edaa316134c41f8160973"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"
# world_address = "0x4e1fde3268e5fd9d18b89d6f08ce42a8ae7098e44af596bad689ceb50ad29ba"

# Madara testnet
# rpc_url = "https://api.cartridge.gg/x/zdefender/katana"
# account_address = "0x3ce7cbb5d8ed56fca0e6b602d0ad249ea393b096675aaaef496f9b4a1121aab"
# private_key = "0x1936d3fa8ba81d2c8744868afb7b48eb61fc96db7a7e008be1176acfb3cd2a0"
# world_address = "0x4e1fde3268e5fd9d18b89d6f08ce42a8ae7098e44af596bad689ceb50ad29ba"
# torii = https://api.cartridge.gg/x/zknight/torii/graphql
